### ISSUE TITLE
Feature request: edit/remove/re-try posts

### ISSUE THREAD

**Issue by mblaney** [gRegorLove/indiebookclub#13]
From IRC for context: https://chat.indieweb.org/dev/2019-11-05/1572994363806200

I created a post which didn't get added to my website due to a micropub endpoint bug, so it would be good to be able to retry posting an existing repost, or not creating the post on indiebookclub when an error is returned from the micropub endpoint.

**Comment by tw2113** [comment]
Would be a good feature to have, especially if doing a lot of quick posts for testing sake with getting information into our own sites.

**Comment by gRegorLove** [comment]
Delete is now supported, including the option for micropub users to re-authorize and send micropub delete requests. https://indiebookclub.biz/updates#post-2021-12-03

Leaving issue open as I plan to add micropub re-try in the future.
