### ISSUE TITLE
Having to reregister micro.blog account each time I enter a new book

### ISSUE THREAD

**Issue by DavidWJ19** [gRegorLove/indiebookclub#17]
The title says it all. My list of books appears not to require re-registering, but I appear to be logged out after a few days (I am not clear yet on the timeline).

**Comment by gRegorLove** [comment]
@DavidWJ19 Can you tell me your micro.blog URL?

Do you mean each time you log in it goes through the Micropub discovery process where it says "Awesome! We found your Micropub endpoint" and gets your confirmation? You should only be prompted for that process once, though if you click "Reset Login" on the settings page, the app will forget your Micropub information and prompt you again on next login.

Your indiebookclub session should last as long as the browser is open or until cookies are cleared. If you close the browser and come back, it's expected you'll need to enter your URL again to log in.

**Comment by DavidWJ19** [comment]
My micro.blog URL is microblog.crossingthethreshold.net.

My list of books read, etc stays viewable without having to log back in, but unless I am doing something wrong (quite possible), I have to log back in when I want to enter a new book. How do I get back to my page to enter a new book? I am not closing the browser or clearing cookies.

**Comment by gRegorLove** [comment]
I double-checked and it looks like cookie lifetime is 7 days, not browser-session-based (I should probably change that). It looks like your two posts were 8 days apart, so that might explain it.

When you're logged in, there's a link at the bottom of each page for "New Post". The homepage should also say "you are signed in as microblog.crossingthethreshold.net." If you're getting logged out in under 7 days, it might be a browser issue; maybe some extensions are interfering with cookies?

[Your profile URL](https://indiebookclub.biz/users/microblog.crossingthethreshold.net) is always public, by the way, so you don't need to be logged in to view your posts.

**Comment by DavidWJ19** [comment]
I am not seeing the "New Post" at the bottom of the, and the homepage is simply the page that one sees before signing up. The only page that I see registering that I am signed in is the list of books I've read, etc.

I am using Firefox. I have a few extensions installed, I'll try disabling them one at a time and see what happens.

**Comment by DavidWJ19** [comment]
I disabled each extension that I had, one at a time refreshing the indiebookclub page each time. "New Post" has not appeared.

**Comment by DavidWJ19** [comment]
I have now signed back in, both on Firefox and Safari (all extensions activated on both browsers). I am now seeing "New Post," and other menu options in both browsers. Maybe it is the cookie lifetime issue that you spoke of?

**Comment by gRegorLove** [comment]
> I am not seeing the "New Post" at the bottom of the, and the homepage is simply the page that one sees before signing up.

Ok, that means you need to log in.

> The only page that I see registering that I am signed in is the list of books I've read, etc.

That page is public; seeing it doesn't mean you're logged in.

**Comment by DavidWJ19** [comment]
So I think what was happening is that because I had bookmarked the URL for the page showing what I had read, etc, indiebookclub appears able to show that page even if I am logged out. Because of that, I assumed that I was logged in.

Based on what you said earlier, it seems that I was probably logged out as my browser had been closed a overnight.

Definitely the confusing part for me was seeing what I had read and so assuming that I was logged in, what in fact I wasn't.

Thank you.

**Comment by gRegorLove** [comment]
Aha, sorry for that confusion. I'll work on adding a Sign In / Sign Out prompt at the top so it's more clear on every page.

**Comment by gRegorLove** [comment]
With the latest update, the page header includes a dynamic Sign In / Sign Out link based on whether you're logged in. It also will indicate the domain you are signed in as and a link to your profile page. Profile pages are always public. On your profile page, if you're logged in there is also a "New Post" button at the top now, in addition to the page footer.

https://indiebookclub.biz/updates#post-2021-12-03
