### ISSUE TITLE
Improve error handling based on granted scopes

### ISSUE THREAD

**Issue by gRegorLove** [gRegorLove/indiebookclub#21]
From some debugging with @nsmsn today, I realized it's possible for an IndieAuth Server to respond with scopes that IBC doesn't currently support, like `draft`. 

Look into improving support for `draft` scope and improve messaging if a Server responds with scopes that IBC doesn't support.

**Comment by dshanske** [comment]
https://github.com/indieweb/micropub-extensions/issues/24

**Comment by gRegorLove** [comment]
Launched with [v0.1.2](https://github.com/gRegorLove/indiebookclub/blob/main/CHANGELOG.md#012-2024-04-07)
