### ISSUE TITLE
Persist /new params through login

### ISSUE THREAD

**Issue by martymcguire** [gRegorLove/indiebookclub#22]
Hello! Love indiebookclub dot biz. Long time user!

One feature I really like is that the `/new` path understands query string arguments for `title`, `authors`, `tags`, `isbn`, etc.

For example:

https://indiebookclub.biz/new?title=Let+This+Radicalize+You%3A+Organizing+and+the+Revolution+of+Reciprocal+Care&authors=Kelly+Hayes%2C+Mariame+Kaba%2C+Harsha+Walia%2C+et+al.&isbn=9781642598278&tags=books

This is super convenient when paired with a bookmarklet that, for example, can pull the relevant pieces off of a Goodreads or Bookshop page and send me over to indiebookclub dot biz.

The problem is - indiebookclub dot biz sessions aren't very long-lived. So typically I get redirected right away to the indiebookclub dot biz sign-in page.

After completing the IndieAuth flow, I'm returned to the `/new` page, but none of the arguments from the initial URL are in the form. It's blank, as if I had logged in and then visited `/new` without any query string arguments. (Because, from its perspective, that is what I did.)

It would be so so so great if the indiebookclub dot biz could hang onto these through the entire sign-in process and show the pre-filled form values after completing sign-in!

**Comment by gRegorLove** [comment]
Sounds good! I'll work on that and check on the session length, too. I think it should be set to last as long as the browser is open, but maybe not.

Aside, I'm also really curious about the bookmarklets you use! I set up those query params intending to set up bookmarklets myself but never got around to it!

**Comment by martymcguire** [comment]
Exciting! Thanks, @gRegorLove!

Session-wise, I can confirm that I have a cookie named `indiebookclub` that has a `Session` expiry from my sign-in yesterday. However! On visiting the home page I am presented with the sign-in prompt rather than the "you are signed in as..." info. My guess is that the session storage for PHP on the server is set to expire after some hours.

Happy to share bookmarklets! Here they are in somewhat readable JavaScript format. You can use a bookmarklet editor like https://www.gibney.org/bookmarklet_editor to convert them to escaped `javascript:...` URLs for actual bookmarklets.

One note is that I add a 'books' tag to all my read posts. You can update or remove that `tags` attribute as you like!

GoodReads: grab the JSON-LD island and yoink the bits:

```javascript
let b=JSON.parse(document.querySelector('script[type="application/ld+json"]').textContent);
let s=new URLSearchParams({title: b.name, isbn: b.isbn, tags:'books', authors: b.author[0]['name']});
window.location='https://indiebookclub.biz/new?'+s.toString();
```

Bookshop: extract the bits from meta tags:

```javascript
let [title, authors]=document.querySelector('meta[property="og:title"]').attributes['content'].textContent.split(' a book by ');
let isbn=document.querySelector('meta[property="book:isbn"]').attributes['content'].textContent;
let s=new URLSearchParams({title, authors, isbn, tags:'books'});
window.location='https://indiebookclub.biz/new?'+s.toString();
```

**Comment by gRegorLove** [comment]
I have a beta version you can test. I added `martymcgui.re` to the allowlist to sign in to https://dev.indiebookclub.biz/. Let me know if you have different domain you'd like to test with.

1. Open [this /new link](https://dev.indiebookclub.biz/new?title=Let+This+Radicalize+You%3A+Organizing+and+the+Revolution+of+Reciprocal+Care&authors=Kelly+Hayes%2C+Mariame+Kaba%2C+Harsha+Walia%2C+et+al.&isbn=9781642598278&tags=books) and you should be redirected to the homepage. It should show a warning now, too, "Please sign in again." It's a one-time flash message so it will go away if you refresh the homepage, but the original query params should still be stored in the session.
2. Sign in and you should end up back on the /new page with the params populated
3. Sign out then try it again with different query parameters

**Comment by martymcguire** [comment]
That worked as your testing steps described! Very exciting! :sparkles: Thank you! :tada:

**Comment by gRegorLove** [comment]
And thanks for the bookmarklet pointers! If you'd like to write up a tutorial on your site I'd be happy to link them in the docs. 

It looks fairly straightforward (knock on wood), so maybe IBC could even have drag-to-toolbar buttons for people to add these to their browser. I'll file a separate issue for that.

**Comment by gRegorLove** [comment]
Launched with [v0.1.2](https://github.com/gRegorLove/indiebookclub/blob/main/CHANGELOG.md#012-2024-04-07)
