### ISSUE TITLE
Feature: Support the `visibility` property

### ISSUE THREAD

**Issue by grantcodes** [gRegorLove/indiebookclub#4]
I would like to use the app, but don't really want to fill up my main feed with reading posts.

It would be great if it supported the `visibility` property so I could make posts unlisted or private.

Would probably make sense as a hidden option in the advanced section.

**Comment by gRegorLove** [comment]
Sounds easy enough. For my future reference: https://indieweb.org/Micropub-extensions#Visibility

**Comment by gRegorLove** [comment]
This is implemented now: https://indiebookclub.biz/updates#post-2021-12-03
